{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezt.ads",
    "module": "eztech-ads-com-cp-livetv-iptvplayer",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.libraries.ads.mobile.sdk",
          "module": "ads-mobile-sdk",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "eztech-ads-com-cp-livetv-iptvplayer-1.0.8.aar",
          "url": "eztech-ads-com-cp-livetv-iptvplayer-1.0.8.aar",
          "size": 494953,
          "sha512": "e207bbdea6947bfce18d8a7477b2b422fb74cafe1c530deddaeae49ba9dd5c06046ae974a93476d5142eff5a686e5667f93d7b75a9e34ae2f54ff26730a85a89",
          "sha256": "95300969fd79ea7751e5bbbfdc2ec837213a3d03c2cb491dd0378b1292a9f951",
          "sha1": "ff3dea0a597cb2bcc69eda24dd73b968b4a52909",
          "md5": "a02edd0dc1286a33493418c41faad730"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.2"
          }
        },
        {
          "group": "com.intuit.sdp",
          "module": "sdp-android",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.intuit.ssp",
          "module": "ssp-android",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.libraries.ads.mobile.sdk",
          "module": "ads-mobile-sdk",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "eztech-ads-com-cp-livetv-iptvplayer-1.0.8.aar",
          "url": "eztech-ads-com-cp-livetv-iptvplayer-1.0.8.aar",
          "size": 494953,
          "sha512": "e207bbdea6947bfce18d8a7477b2b422fb74cafe1c530deddaeae49ba9dd5c06046ae974a93476d5142eff5a686e5667f93d7b75a9e34ae2f54ff26730a85a89",
          "sha256": "95300969fd79ea7751e5bbbfdc2ec837213a3d03c2cb491dd0378b1292a9f951",
          "sha1": "ff3dea0a597cb2bcc69eda24dd73b968b4a52909",
          "md5": "a02edd0dc1286a33493418c41faad730"
        }
      ]
    }
  ]
}
